version: "3"
services:
  chr:
    container_name: mikrotik
    image: marlirukmana/routeros:6.49.15
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "80:80"
      - "8291:8291"
      - "13231:13231/udp"
